apiVersion: apps/v1
kind: Deployment
metadata:
  name: minikube-deployment
  labels:
    app: demo-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: master6789/minikube
        ports:
        - containerPort: 8089
          
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: demo-app
  type: NodePort  
  ports:
    - port: 8089
      targetPort: 8089
      nodePort: 30008
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: demo-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: demo-app
